name: Build and Push Services
run-name: build-services

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE: test-front:latest

jobs:
  build-payment:
    name: build and push payment image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: create env file.
        env:
          CLIENT_ENV: frontend
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_USERNAME}}
          envkey_SOME_API_KEY: "123456abcdef"
          some_other_variable: foobar
        run: |
          chmod u+x ./env.sh
          ./env.sh

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build and push image to registry
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE}} -f dev.Dockerfile .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE}}

      # - name: build and push image to registry
      #   uses: docker/build-push-action@v6
      #   with:
      #     # context: "{{defaultContext}}:frontend"
      #     file: ./frontend/dev.Dockerfile
      #     push: true
      #     tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE}}
